name: shamarasal
favicon: null
layout_spectrum: 0.32678994722664356
typography_spectrum: 0.49368
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefc'
    - '#050a0e'
    - '#6d8798'
    - '#9e0231'
    - '#69473e'
  brandStrength: 0.6110863562207669
  lightness: 0.6875
  saturation: 0
  rhythmicContrast: 0.9477294217795134
purpose: []
